const taskkeysGlobal = [];
let task = {};let subtasksLengthArray = [];
const taskData = {};
let taskkeys = [];
let progressStatusTrue = [];
let TechnicalTask = "Technical Task";
let UserStory = "User Story";
let assignedToUserEditNull = null;
let addTaskArrayEdit = [];
let expandedEdit = false;
let selectedPrioEdit = null;
let subtasksArrayEdit = [];
let usersEdit = [];
let fetchImagesEdit = [];
let assignedToUserArrayEdit = [];
let assignedToUserArrayNamesGlobalEdit = [];
let opentaskIndex;
let taskInfo;
let isSaving = false;